#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then run 'sh' with that shell as a wrapper:
#
#           ksh gradlew
#
#       or
#
#           bash gradlew
#
#   (2) This script attempts to find the Gradle home directory using the
#       JAVA_HOME environment variable if it is set. If JAVA_HOME is set, we
#       use that to find the Java executable. If you have a standard Gradle
#       installation, you can set the GRADLE_HOME environment variable to point
#       to, for example, /opt/gradle/gradle8.5 (or wherever you installed it).
#       If you neither have JAVA_HOME nor GRADLE_HOME, we try to find Gradle
#       using the "gradle" command on the PATH. As a last resort, we attempt to
#       download the Gradle distribution from the internet. For this to work,
#       you must be using a POSIX shell and have a connection to the internet.
#
#   (3) You need a Java installation to run Gradle. If you don't have Java,
#       you can install it with the "sdkmanager" tool that comes with Gradle,
#       available from https://gradle.org/install/#sdkman.
#
#   (4) We also try to make the script work on old versions of Solaris,
#       where /bin/sh is sometimes noncompliant, but it also has a /usr/xpg4/bin/sh.
#       Unless we are on Solaris, we try to use the system sh as the shell.
#
#   (5) On Solaris, if we can't find /usr/xpg4/bin/sh, we fall back to /bin/sh,
#       which may be noncompliant, but we have no choice.
#
#   (6) If you have any problems, please set the DEBUG variable to "true" as
#       a temporary measure.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$(ls -ld "$app_path")
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
# Discard cd standard output in case $CDPATH is set (https://github.com/gradle/gradle/issues/25036)
APP_HOME=$( cd "${APP_HOME:-./}" > /dev/null && pwd -P ) || exit

# Use the maximum available file descriptors if we can.
if command -v ulimit > /dev/null 2>&1; then
    ulimit -n 4096 || true
fi

# Use the maximum available file descriptors for Gradle daemon if we can.
if command -v ulimit > /dev/null 2>&1 && [ -n "$(ulimit -n)" ]; then
    GRADLE_OPTS="$GRADLE_OPTS -Dorg.gradle.daemon.numericalMaxFileDescriptors=$(ulimit -n)"
fi

# OS specific support.  $var _must_ be set to either true or false.
cygwin=false
darwin=false
os400=false
case "$(uname)" in
  CYGWIN* | MSYS* | MINGW*)
    cygwin=true
    ;;
  Darwin*)
    darwin=true
    ;;
  OS400*)
    os400=true
    ;;
esac

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java > /dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if [ "$cygwin" = "false" ] && [ "$darwin" = "false" ] && [ "$os400" = "false" ] ; then
    MAX_FD_LIMIT=$(ulimit -n)
    if [ $? -eq 0 ] ; then
        if [ "$MAX_FD_LIMIT" -le 2048 ] ; then
            GRADLE_OPTS="$GRADLE_OPTS -Dorg.gradle.daemon.maxFileDescriptors=2048"
        else
            GRADLE_OPTS="$GRADLE_OPTS -Dorg.gradle.daemon.maxFileDescriptors=$MAX_FD_LIMIT"
        fi
    fi
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if dedicated module appears)
#   * @argument99999 files

# The default value for stopping the daemon is 'stop'. We set this to 'stop' when
# no other stop commands are found, using a test to see if the value exists.
if [ -z "$GRADLE_STOP_DAEMON_OPTS" ] ; then
    GRADLE_STOP_DAEMON_OPTS="stop"
fi

# Argument separators (for handling annotations like @ArgumentsFiles).
classpath_separator=:
if $cygwin ; then
    classpath_separator=";"
fi

# Increase the maximum number of arguments for Windows command line.
if [ -n "$MSYSTEM" ] ; then
    MAX_ARGUMENTS_LENGTH=32000
else
    MAX_ARGUMENTS_LENGTH=131072
fi

# Determine the Gradle home from the path to this script (if it exists).
if $cygwin ; then
    GRADLE_HOME=$(cygpath -u "$GRADLE_HOME")
fi

if [ -n "$GRADLE_HOME" ] ; then
    # Handle the case where $GRADLE_HOME is not a directory.
    if [ ! -d "$GRADLE_HOME" ] ; then
        die "ERROR: GRADLE_HOME is set to an invalid directory: $GRADLE_HOME"
    fi
    GRADLE_HOME=$(cd "$GRADLE_HOME" > /dev/null && pwd -P)
    GRADLE_WRAPPER_SCRIPT="$GRADLE_HOME/gradle/wrapper/gradle-wrapper.jar"
    # Fix for macOS not having `readlink -f` for symlinks.
    if [ -h "$GRADLE_WRAPPER_SCRIPT" ]; then
        GRADLE_WRAPPER_SCRIPT=$(readlink "$GRADLE_WRAPPER_SCRIPT")
        GRADLE_WRAPPER_SCRIPT_DIR=$(dirname "$GRADLE_WRAPPER_SCRIPT")
        if [ -n "$GRADLE_WRAPPER_SCRIPT_DIR" ]; then
            GRADLE_HOME=$(cd "$GRADLE_WRAPPER_SCRIPT_DIR/.." > /dev/null && pwd -P)
        fi
    fi
    GRADLE_WRAPPER_JAR="$GRADLE_HOME/lib/gradle-wrapper.jar"
else
    GRADLE_WRAPPER_JAR="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"
fi

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    JAVACMD="$JAVA_HOME/bin/java"
else
    JAVACMD=java
fi

# Attempt to find the Gradle wrapper jar.
if [ ! -f "$GRADLE_WRAPPER_JAR" ]; then
    if [ -f "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" ]; then
        GRADLE_WRAPPER_JAR="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"
    else
        # Download the Gradle distribution if the wrapper jar is not found.
        echo "Downloading Gradle distribution..."
        DIST_DIR="$APP_HOME/gradle/wrapper/dists"
        DIST_NAME="gradle-8.5-bin.zip"
        mkdir -p "$DIST_DIR"
        curl -L -o "$DIST_DIR/$DIST_NAME" "https://services.gradle.org/distributions/gradle-8.5-bin.zip"
        unzip -q "$DIST_DIR/$DIST_NAME" -d "$DIST_DIR"
        GRADLE_HOME="$DIST_DIR/$(ls $DIST_DIR | grep gradle-8.5)"
        GRADLE_WRAPPER_JAR="$GRADLE_HOME/lib/gradle-wrapper.jar"
    fi
fi

# Execute Gradle
exec "$JAVACMD" \
      -classpath "$GRADLE_WRAPPER_JAR" \
      org.gradle.wrapper.GradleWrapperMain \
      "$@"
